### ISSUE TITLE
Apple Silicon compatibility

### ISSUE THREAD

**Issue by adamcypher** [badboy/rocketscience#1]
Quick question: what is required to get this example to work on Apple Silicon?

`building for macOS-x86_64 but attempting to link with file built for macOS-arm64`

**Comment by badboy** [comment]
It should just work for the code in this repository (I'm on an M1 myself).

For everything else you should describe in more detail what you're doing.

**Comment by adamcypher** [comment]
Apologies. I can leave this issue here despite my own embarrassment, if other people run into the same.

Had at some point configured terminal to run under Rosetta 2 and evidently failed to switch it back.

`uname -m` must return `arm64` on Apple Silicon otherwise swift compiler will compile for the wrong architecture and won't link to the rust dylib.

**Comment by badboy** [comment]
Don't worry. I've run into that several times now (in both directions). Glad you were able to figure it out.
